name: Deploy (git pull + PM2)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Update code and restart
        run: |
          echo "hello from runner"
          cd /home/node86/fitness-app-web-server
          git fetch --all
          git reset --hard origin/main
          npm ci
          npm run build
          npm run server:build
          pm2 reload ecosystem.config.cjs --env production
          pm2 save
